name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradlew Executable
        run: chmod +x gradlew
        working-directory: AndroidApp

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: AndroidApp

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
